<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Content Include="README.md" />
    <Compile Include="001.Sum of Digits.fs" />
    <Compile Include="Library.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FsUnit" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="6.0.1" />
  </ItemGroup>

</Project>
